// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type LoginUser struct {
	Nickname string `json:"nickname"`
	Email    string `json:"email"`
	DeviceID string `json:"deviceId"`
}

type Mutation struct {
}

type Query struct {
}

type TextToSpeech struct {
	Text string `json:"text"`
}

type TranslateText struct {
	Text           string `json:"text"`
	SourceLanguage string `json:"sourceLanguage"`
	TargetLanguage string `json:"targetLanguage"`
}

type User struct {
	ID        int64     `json:"id"`
	Nickname  string    `json:"nickname"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type UserDevice struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"userId"`
	DeviceID  string    `json:"deviceId"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}
